Create caniuse.ts
nhcarrigan/Becca-Lyria pull request #450
Opened 2021-01-04 15:05 UTC by Galaxy-Coding

# Pull Request

I read them

## Description:

added a simple caniuse command

## Related Issue:

Closes #XXXXX

## Scope:

Did you remember to update the `package.json` version number?

- [ ] Major Version Update: X.\_.\_ (for complete code refactors, or large PRs that adjust most of the codebase)
- [ ] Minor Version Update: \_.X.\_ (for the addition of new commands)
- [ ] Patch Version Update: \_.\_.X (for bug fixes _in the code_.)
- [ ] No Version Update: \_.\_.\_ (no version update for additions to tests, documentation, or anything that isn't end-user facing.)

## Documentation:

For _any_ version updates, please verify if the [documentation page](https://beccalyria.nhcarrigan.com) needs an update. If it does, please [create an issue there](https://github.com/nhcarrigan/Becca-Lyria-documentation/issues/new?assignees=nhcarrigan&labels=%F0%9F%9A%A6+status%3A+awaiting+triage&template=update.md&title=%5BUPDATE%5D) to ensure it is not forgotten.

- [ ] My contribution does NOT require a documentation update.
- [ ] My contribution DOES require a documentation update.

2021-01-05 15:17 UTC, Galaxy-Coding commented
I’m not sure what version is should change the config.js to, so please let me know

2021-01-05 15:21 UTC, nhcarrigan commented
Becca's current version in the `package.json` file is `9.0.3` - because this PR adds a new command, it's a minor version change, so the version should be bumped to `9.1.0`. 🙂

2021-01-05 15:30 UTC, nhcarrigan requested changes
A couple of quick suggestions.

2021-01-05 15:30 UTC, nhcarrigan commented on src/commands/general/caniuse.ts
> +      const feature = commandArguments.shift();
```suggestion
      const feature = commandArguments.join("-");
```
`.shift()` will only take the first argument - in this case, we want all of them.

2021-01-05 15:30 UTC, nhcarrigan commented on src/commands/general/caniuse.ts
> +          .setImage(`https://caniuse.bitsofco.de/image/${feature.replace(/ /g,'-')}.webp`)
```suggestion
          .setImage(`https://caniuse.bitsofco.de/image/${feature}.webp`)
```
If we use `join` above with a `-` instead of spaces, we can skip the replace step here.

2021-01-05 15:34 UTC, Galaxy-Coding commented on src/commands/general/caniuse.ts
> +          .setImage(`https://caniuse.bitsofco.de/image/${feature.replace(/ /g,'-')}.webp`)
thank you, i think that’s better

2021-01-05 15:50 UTC, nhcarrigan approved these changes
LGTM~! 🥳 

Congratulations on your first pull request to this project! We look forward to future contributions!

2021-01-05 15:51 UTC, merged

2021-01-05 15:52 UTC, Galaxy-Coding commented
Thank you so much!

2021-01-06 16:34 UTC, nhcarrigan commented
@all-contributors please add @Galaxy-Coding for code